title: Home
iconURL: assets/default-icon2.png
theme: jekyll-theme-hacker

# for a clean URL
permalink: :slug

social:
  github: m4rxb

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
